#!/usr/bin/env ruby

require 'vagrant-openstack-plugin'

Vagrant.configure("2") do | config |
    config.vm.box = "openstack-dummy"

    config.ssh.username         = "ec2-user"
    config.ssh.private_key_path = "~/.ssh/id_rsa"

    config.vm.provision :puppet do |puppet|
        puppet.module_path = "modules"
    end

    config.vm.provider :openstack do |os|
        os.endpoint        = "#{ENV['OS_AUTH_URL']}/tokens"
        os.username        = "#{ENV['OS_USERNAME']}"
        os.api_key         = "#{ENV['OS_PASSWORD']}"
        os.tenant          = "#{ENV['OS_TENANT_NAME']}"
        os.region          = "#{ENV['OS_REGION_NAME']}"

        os.flavor          = /m1.small/
        os.image           = /centos/
        os.keypair_name    = "walesnix"
        os.floating_ip     = "130.56.244.115"
        #os.security_groups = ["ssh","http"]
        os.security_groups = "ssh"

        # Read the user data
        os.user_data       = File.open('cloud-init','r') {|f| f.read}
    end
end
    
